" basics
syntax on
set clipboard=unnamedplus
set incsearch
set hlsearch
set wildmenu
set showcmd
set ignorecase
set smartcase
set autoindent
set path+=**
set colorcolumn=+1
set dir="~/.vim/"
set tw=80

" languages
autocmd FileType lua setlocal expandtab shiftwidth=4
