let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
	silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
	autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" basics
set background=dark
set clipboard=unnamedplus
set incsearch
set hlsearch
set wildmenu
set showcmd
set ignorecase
set smartcase
set autoindent
set path+=**
set scrolloff=10
set colorcolumn=+1
set dir="~/.vim/"
set rnu nu

" plugins
call plug#begin()
Plug 'gboncoffee/cybercafe-vim-theme'
Plug 'tpope/vim-commentary'
Plug 'editorconfig/editorconfig-vim'
call plug#end()

" editor
set tw=80
set nowrap

colorscheme cybercafe
