import = ["~/.config/alacritty/papertheme.toml"]

[font]
size = 10.5

[font.normal]
family = "Fragment Mono"

[selection]
save_to_clipboard = true

[window.dimensions]
columns = 80
lines = 24

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
   { key = "v", mods = "Control|Shift", action = "Paste" },
   { key = "c", mods = "Control|Shift", action = "Copy" }
]
