import = ["~/.config/alacritty/papertheme.toml"]

[font]
size = 9.0

[font.normal]
family = "LiberationMono"

[selection]
save_to_clipboard = true

[window.dimensions]
columns = 80
lines = 24

[window.position]
x = 300
y = 300

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
   { key = "v", mods = "Control|Shift", action = "Paste" },
   { key = "c", mods = "Control|Shift", action = "Copy" }
]
