[font]
size = 8.0

[font.normal]
family = "Liberation Mono"

[selection]
save_to_clipboard = true

[window.dimensions]
columns = 80
lines = 24

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" },
   { key = "v", mods = "Control|Shift", action = "Paste" },
   { key = "c", mods = "Control|Shift", action = "Copy" }
]

# (Github Light High Contrast w/ better bg/fg)

# Default colors
[colors.primary]
background = '#ffffea'
foreground = '#000000'

# Cursor colors
[colors.cursor]
text = '#ffffff'
cursor = '#000000'

# Normal colors
[colors.normal]
black = '#0e1116'
red = '#a0111f'
green = '#024c1a'
yellow = '#3f2200'
blue = '#0349b4'
magenta = '#622cbc'
cyan = '#1b7c83'
white = '#66707b'

# Bright colors
[colors.bright]
black = '#4b535d'
red = '#86061d'
green = '#055d20'
yellow = '#4e2c00'
blue = '#1168e3'
magenta = '#622cbc'
cyan = '#1b7c83'
white = '#66707b'
