import = ["~/.config/alacritty/papertheme.toml"]

[colors.primary]
background = "#eaffea"

[font]
size = 10.0

[font.normal]
family = "Fragment Mono"

[window]
title = "Login"
dynamic_title = false

[window.dimensions]
columns = 50
lines = 12

[window.position]
x = 1313

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
   { key = "v", mods = "Control|Shift", action = "Paste" },
   { key = "c", mods = "Control|Shift", action = "Copy" }
]
