theme = "dracula"

[editor]
line-number  = "relative"
scrolloff    = 10
bufferline   = "multiple"
color-modes  = true
gutters      = [ "diff", "diagnostics", "line-numbers", "spacer" ]
idle-timeout = 0

[editor.file-picker]
hidden = false

[editor.statusline]
left   = [ "mode", "file-type", "workspace-diagnostics" ]
center = [ "file-name" ]
right  = [ "position", "total-line-numbers" ]

[keys.normal]
tab     = ":bn"
"S-tab" = ":bp"
X       = "extend_line_above"
J       = "copy_selection_on_next_line"
K       = "copy_selection_on_prev_line"
